[package]
name = "dynasty"
version = "0.1.0"
edition = "2021"
description = "Desktop terminal for cryptocurrency exchanges"
[package.metadata.bundle]
name = "Dynasty"
identifier = "io.github.me.dynasty"
icon = ["assets/dynasty.icns"]

[dependencies]
binance-rs-async = { version = "1.3.3", default-features = false, features = ["rustls-tls", "wallet_api"] }
chrono = "0.4.31"
iced = { version = "0.12.0", features = ["tokio", "debug", "lazy", "svg", "image", "advanced", "canvas"] }
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.114"
tokio = { version = "1.37.0", default-features = false, features = ["sync", "macros", "time"] }
ngnk = { path = "crates/ngnk", optional = true }
meval = { version = "0.2.0", optional = true }
plotters = "0.3.5"
plotters-iced = "0.10.0"
phf = "0.11.1"
regex = "1.10.4"
ringbuf = "0.3.3"
ahash = "0.8.11"

# logging
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }

# loader widget
lyon_algorithms = "1.0.4"

# websocket
iced_futures = "0.12.0"
tungstenite = { version = "0.21.0", default-features = false }

[features]
default = ["calculator_meval"]

calculator_k = ["dep:ngnk"]
calculator_meval = ["dep:meval"]

[build-dependencies]
phf_codegen = "0.11.1"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
directories-next = "2.0"
[target.'cfg(target_arch = "wasm32")'.dependencies]
web-sys = { version = "0.3", features = ["Window", "Storage"] }

[patch.crates-io]
binance-rs-async = { git = "https://github.com/Fogapod/binance-rs-async", rev = "fb2a1daf1063d3b7edb551d4dc8ef8d4d7197538" }

[profile.release]
codegen-units = 1
lto = true
strip = true
